# Install the apt prerequisites
sudo: required
addons:
  apt:
    packages:
      - python-pygments

# Build the website
script:
  - ls
  - ls ./binary
  - sudo ./binary/hugo -d .

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: .
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master